### ISSUE TITLE
The size of tensor a (4096) must match the size of tensor b (4097) at non-singleton dimension 3

### ISSUE THREAD

**Issue by Cola-any** [apple/ml-slowfast-llava#2]
Hello, thank you for sharing your excellent project. 

When I evaluated it on the multiple-choice QA benchmark **EgoSchema**, I found that the prompt was long than other bench (I guess this may cause the problem below). 
The following error occurred:

`Traceback (most recent call last): 

  File "/home/user/MLLM/ml-slowfast-llava/run_inference_multiple_choice_qa.py", line 185, in <module>
    run_inference(args) \
  File "/home/user/MLLM/ml-slowfast-llava/run_inference_multiple_choice_qa.py", line 136, in run_inference
    output = llava_inference( \
  File "/home/user/MLLM/ml-slowfast-llava/run_inference_multiple_choice_qa.py", line 56, in llava_inference
    output_ids = model.generate( \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs) \
  File "/home/user/MLLM/ml-slowfast-llava/slowfast_llava/llava/model/language_model/llava_llama.py", line 138, in generate
    return super().generate( \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs) \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1544, in generate
    return self.greedy_search( \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2404, in greedy_search \
    outputs = self( \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl \
    return self._call_impl(*args, **kwargs) \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl \
    return forward_call(*args, **kwargs) \
  File "/home/user/MLLM/ml-slowfast-llava/slowfast_llava/llava/model/language_model/llava_llama.py", line 91, in forward \
    return super().forward( \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1176, in forward \
    outputs = self.model( \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl \
    return self._call_impl(*args, **kwargs) \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl \
    return forward_call(*args, **kwargs) \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 993, in forward \
    causal_mask = self._update_causal_mask(attention_mask, inputs_embeds) \
  File "/home/user/anaconda3/envs/sf_llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1079, in _update_causal_mask \
    padding_mask = causal_mask[..., :mask_length].eq(0.0) * attention_mask[:, None, None, :].eq(0.0) \
RuntimeError: The size of tensor a (4096) must match the size of tensor b (4097) at non-singleton dimension 3`

And I found that this error can be bypassed by setting `max_new_tokens=128` in [here ](https://github.com/apple/ml-slowfast-llava/blob/bea0f73c106b91404ef403353e184b278fcc64a7/run_inference_multiple_choice_qa.py#L62)(the default value is 128). But I still don't quite understand what caused this error. Especially why this cannot be solved by increasing rope_scaling_factor. Can you explain it for me?

Thank you very much. Best regards.

**Comment by xumingze0308** [comment]
I cannot reproduce this error. I think this can be caused by the Transformer version per https://discuss.huggingface.co/t/runtimeerror-the-size-of-tensor-a-4096-must-match-the-size-of-tensor-b-4097-at-non-singleton-dimension-3/103585.

**Comment by Cola-any** [comment]
Thank you for your reply. 

The transformers version in my env is the same as [here](https://github.com/apple/ml-slowfast-llava/blob/bea0f73c106b91404ef403353e184b278fcc64a7/pyproject.toml#L17) (**4.38.2**), and I create the conda env following your suggestion [here](https://github.com/apple/ml-slowfast-llava#installation). 

I try to update the transformers version to 4.44 per https://discuss.huggingface.co/t/runtimeerror-the-size-of-tensor-a-4096-must-match-the-size-of-tensor-b-4097-at-non-singleton-dimension-3/103585, but encountered incompatibility issues as follows:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`
`sf-llava 1.2.2.post1 requires tokenizers==0.15.1, but you have tokenizers 0.19.1 which is incompatible.`
`sf-llava 1.2.2.post1 requires transformers==4.38.2, but you have transformers 4.44.0 which is incompatible.`

As you cannot reproduce this error, I wonder if your env or code has been updated locally, which may be different from this Rep. Can you share your latest env configuration? By the way, my env list:
![cdcd0053d3a10be9114c5031d282880](https://github.com/user-attachments/assets/6138bf40-9303-43af-9051-bc5f54b6763b)

**Comment by geomlyd** [comment]
Hey, I don't currently have a solution either, but I when I tried to use 4.44 I actually got some sort of LLaVA-config related error (`'LlavaConfig' object has no attribute 'mlp_bias'`, presumably has to do with the pretrained LLM) and was unable to run the code at all. With 4.38 I run into the same issue (although in a different use case where I was porting inference on another dataset).

**Comment by Cola-any** [comment]
I appreciate your timely response. 
The error is fixed now (at least for now) and it is indeed caused by transformers version. 
When I install transformers **4.40.0**, even though it prompts incompatibility, the project can run normally and the results are correct. 
Maybe you can try to update transformers to 4.40.0 in your use case.

Have a nice day.
